// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from StringMessage.djinni

#import "SMStringMessage+Private.h"
#import "SMStringMessage.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SMStringMessage ()

- (id)initWithCpp:(const std::shared_ptr<::stringmessage::StringMessage>&)cppRef;

@end

@implementation SMStringMessage {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::stringmessage::StringMessage>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::stringmessage::StringMessage>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable SMStringMessage *)create {
    try {
        auto objcpp_result_ = ::stringmessage::StringMessage::create();
        return ::djinni_generated::StringMessage::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getStringMessage {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_string_message();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto StringMessage::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto StringMessage::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SMStringMessage>(cpp);
}

}  // namespace djinni_generated

@end
