// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from StringMessage.djinni

#import <Foundation/Foundation.h>
@class SMStringMessage;


@interface SMStringMessage : NSObject

+ (nullable SMStringMessage *)create;

- (nonnull NSString *)getStringMessage;

@end
